create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  domain text,
  industry text,
  notes text,
  owner_id uuid references public.profiles(id) on delete set null,
  -- Account extended fields
  phone text,
  fax text,
  website text,
  ticker_symbol text,
  ownership text,
  employees int,
  sic_code text,
  rating text,
  account_type text,
  account_number text,
  account_site text,
  annual_revenue numeric(18,2),
  billing_street text,
  billing_city text,
  billing_state text,
  billing_zip text,
  billing_country text,
  shipping_street text,
  shipping_city text,
  shipping_state text,
  shipping_zip text,
  shipping_country text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id uuid primary key default gen_random_uuid(),
  first_name text not null,
  last_name text,
  email text,
  phone text,
  title text,
  company_id uuid references public.companies(id) on delete set null,
  owner_id uuid references public.profiles(id) on delete set null,
  notes text,
  -- Contact extended fields
  mobile text,
  fax text,
  website text,
  secondary_email text,
  twitter text,
  skype_id text,
  email_opt_out boolean not null default false,
  date_of_birth date,
  assistant text,
  asst_phone text,
  department text,
  lead_source text,
  description text,
  mailing_street text,
  mailing_city text,
  mailing_state text,
  mailing_zip text,
  mailing_country text,
  other_street text,
  other_city text,
  other_state text,
  other_zip text,
  other_country text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pipeline_stages (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  position int not null,
  is_won boolean not null default false,
  is_lost boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.deals (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  amount numeric(12, 2),
  currency text not null default 'USD',
  stage_id uuid not null references public.pipeline_stages(id),
  contact_id uuid references public.contacts(id) on delete set null,
  company_id uuid references public.companies(id) on delete set null,
  owner_id uuid references public.profiles(id) on delete set null,
  expected_close_date date,
  closed_at timestamptz,
  position int not null default 0,
  type text,
  next_step text,
  lead_source text,
  probability int check (probability is null or (probability >= 0 and probability <= 100)),
  campaign_source text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

