#!/usr/bin/env python3
"""
Generate a Supabase migration that upserts the Skilldora custom RA template
and assigns it to Skilldora's ra_associates row.

Reads:
    public/demo-skilldora.html  → goes into ra_landing_templates.demo_html

The `html` column (used for /refer/:slug) is intentionally left empty for now —
the public referral form falls back to the BUILTIN_FALLBACK_TEMPLATE in
src/lib/landingTemplate.ts when html is empty, which is the same form the
default-typed RAs use.

Run before each push:
    python3 scripts/emit-skilldora-template-migration.py
    supabase db push --linked
"""

from __future__ import annotations
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
DEMO = ROOT / "public" / "demo-skilldora.html"

# Stable deterministic UUID so the migration is idempotent — re-running the
# generator + db push UPDATEs the same template row instead of creating a new
# one. Picked from /dev/urandom once and pinned here.
TEMPLATE_ID = "c5a11d04-5d11-4d04-9c5a-5d115d04c5a1"

MIGRATION_PATH = (
    ROOT / "supabase" / "migrations" / "20260620120000_skilldora_custom_template.sql"
)


def dollar_tag(html: str) -> str:
    """Pick a $tag$ that's guaranteed not to appear in the HTML."""
    base = "SKD_DEMO"
    n = 0
    while f"${base}{n if n else ''}$" in html:
        n += 1
    return f"{base}{n if n else ''}"


def main() -> None:
    if not DEMO.exists():
        raise SystemExit(
            f"missing {DEMO}\nRun: python3 scripts/build-skilldora-template.py first"
        )
    html = DEMO.read_text()
    tag = dollar_tag(html)

    sql = f"""-- ═══════════════════════════════════════════════════════════════════════════
-- Custom Skilldora-branded demo template
--
-- The first per-RA custom Company template. Branded to myskilldora.com
-- (Skilldora logo in topbar, Roboto Slab + Roboto fonts, orange/blue palette,
-- light background) while keeping the avatar grid + RA section intact. The
-- Divigner logo is intentionally left ONLY in the partnership block inside
-- the RA section.
--
-- Source: public/demo-skilldora.html (generated by
--   scripts/build-skilldora-template.py from public/demo.html).
-- Re-running this migration UPSERTs the same row by its pinned id.
-- ═══════════════════════════════════════════════════════════════════════════

DO $migration$
DECLARE
  v_divigner_org uuid := 'dddddddd-dddd-dddd-dddd-dddddddddddd';
  v_template_id  uuid := '{TEMPLATE_ID}';
BEGIN

  -- 1) Upsert the template row (empty `html` falls back to the default refer
  --    form; only `demo_html` is custom for now).
  INSERT INTO public.ra_landing_templates (
    id, organization_id, name, html, demo_html
  ) VALUES (
    v_template_id,
    v_divigner_org,
    'Skilldora Custom (Company)',
    '',
    ${tag}${html}${tag}$
  )
  ON CONFLICT (id) DO UPDATE
    SET name       = EXCLUDED.name,
        html       = EXCLUDED.html,
        demo_html  = EXCLUDED.demo_html,
        updated_at = now();

  -- 2) Point Skilldora's ra_associates row at this template.
  UPDATE public.ra_associates
     SET template_id = v_template_id
   WHERE slug = 'skilldora';

  RAISE NOTICE 'Skilldora custom template upserted (id=%)', v_template_id;
END
$migration$;
"""

    MIGRATION_PATH.write_text(sql)
    print(f"wrote {MIGRATION_PATH} ({len(sql):,} bytes)")


if __name__ == "__main__":
    main()
